# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build-Test with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda-sample-api-0.0.1-SNAPSHOT.jar
        path: target/lambda-sample-api-0.0.1-SNAPSHOT.jar
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
    - name: Upload Lambda Function
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: updateSeat
        zip_file: function/lambda-sample-api-0.0.1-SNAPSHOT.jar
        dry_run: true
        publish: false
